name: Spring Boot Backend for Tekk Match
on:
  push:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/tekk-match
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/tekk-match
          file: ./backend/tekk-match/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tekk-match-server:latest
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push image to docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/tekk-match
          file: ./backend/tekk-match/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tekk-match-server:latest
